#include "init.h"

void LEDs_ini(void)
{
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN);
	SET_BIT(GPIOD->MODER, GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0);
}

void TIM7_ini(void){
	NVIC_EnableIRQ(TIM7_IRQn);
	SET_BIT(RCC->APB1ENR, RCC_APB1ENR_TIM7EN);
	WRITE_REG(TIM7->PSC, 10000);
	WRITE_REG(TIM7->ARR, 1000);
	WRITE_REG(TIM7->DIER, TIM_DIER_UIE);
	SET_BIT(TIM7->CR1, TIM_CR1_CEN);
}
