#include "init.h"

void LEDs_ini(void)
{
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN);
	WRITE_REG(GPIOD->MODER, GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0);
}

void BUTTON_ini(void)
{
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIOAEN);
	SET_BIT(GPIOA->OSPEEDR, GPIO_OSPEEDER_OSPEEDR0_0);
	SET_BIT(GPIOA->PUPDR, GPIO_PUPDR_PUPDR0_1);
}

