#include "init.h"

void LEDs_ini(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIODEN;
	GPIOD->MODER= GPIO_MODER_MODER12_0 | GPIO_MODER_MODER13_0 | GPIO_MODER_MODER14_0 | GPIO_MODER_MODER15_0;
}

void BUTTON_ini(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->OSPEEDR |= GPIO_OSPEEDER_OSPEEDR0_0;
	GPIOA->PUPDR |= GPIO_PUPDR_PUPDR0_1;
}
