#include "init.h"

void LEDs_ini(void)
{
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN);
	SET_BIT(GPIOD->MODER, GPIO_MODER_MODER12_1 | GPIO_MODER_MODER13_1 | GPIO_MODER_MODER14_1 | GPIO_MODER_MODER15_1);
	WRITE_REG(GPIOD->AFR[1], 0x22220000); //timer4 alt set
}

void TIM4_ini(void){
	SET_BIT(RCC->APB1ENR, RCC_APB1ENR_TIM4EN);
	SET_BIT(TIM4->CCER, TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E | TIM_CCER_CC4E);
	WRITE_REG(TIM4->ARR, 0xFF);
	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2);
	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC2M_1 | TIM_CCMR1_OC2M_2);
	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2);
	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC4M_1 | TIM_CCMR2_OC4M_2); 
	SET_BIT(TIM4->CR1, TIM_CR1_CEN | TIM_CR1_ARPE);
	
}
